"""Brand models - backward compatible re-exports."""

from .brand import (
    AudienceProfile,
    BrandCoreIdentity,
    BrandIdentityFull,
    BrandIndex,
    BrandIndexEntry,
    BrandSummary,
    ColorDefinition,
    CompetitivePositioning,
    TypographyRule,
    VisualIdentity,
    VoiceGuidelines,
)
from .product import (
    PackagingTextDescription,
    PackagingTextElement,
    ProductAttribute,
    ProductFull,
    ProductIndex,
    ProductSummary,
)
from .project import ProjectFull, ProjectIndex, ProjectStatus, ProjectSummary
from .style_reference import (
    AppearanceSpec,
    CanvasSpec,
    ConstraintSpec,
    ContentSpec,
    GeometrySpec,
    InteractionSpec,
    LayoutElement,
    LayoutStructureSpec,
    MessageSpec,
    ProductSlot,
    StyleReferenceAnalysis,
    StyleReferenceAnalysisV2,
    StyleReferenceConstraintsSpec,
    StyleReferenceFull,
    StyleReferenceIndex,
    StyleReferenceSummary,
    StyleSpec,
    VisualSceneSpec,
)

__all__ = [
    # Brand models (11)
    "AudienceProfile",
    "BrandCoreIdentity",
    "BrandIdentityFull",
    "BrandIndex",
    "BrandIndexEntry",
    "BrandSummary",
    "ColorDefinition",
    "CompetitivePositioning",
    "TypographyRule",
    "VisualIdentity",
    "VoiceGuidelines",
    # Product models (6)
    "PackagingTextDescription",
    "PackagingTextElement",
    "ProductAttribute",
    "ProductFull",
    "ProductIndex",
    "ProductSummary",
    # Project models (4)
    "ProjectFull",
    "ProjectIndex",
    "ProjectStatus",
    "ProjectSummary",
    # StyleReference models (18)
    "AppearanceSpec",
    "CanvasSpec",
    "ConstraintSpec",
    "ContentSpec",
    "GeometrySpec",
    "InteractionSpec",
    "LayoutElement",
    "LayoutStructureSpec",
    "MessageSpec",
    "ProductSlot",
    "StyleReferenceAnalysis",
    "StyleReferenceAnalysisV2",
    "StyleReferenceConstraintsSpec",
    "StyleReferenceFull",
    "StyleReferenceIndex",
    "StyleReferenceSummary",
    "StyleSpec",
    "VisualSceneSpec",
]
