"""Brand storage and persistence functions.
Handles reading/writing brand data to ~/.sip-videogen/brands/
"""

__all__ = [
    # base
    "get_brands_dir",
    "get_brand_dir",
    "get_index_path",
    "slugify",
    "validate_slug",
    "safe_resolve_path",
    # index
    "load_index",
    "save_index",
    # brand
    "create_brand",
    "load_brand",
    "load_brand_summary",
    "save_brand",
    "delete_brand",
    "list_brands",
    "update_brand_summary_stats",
    "backup_brand_identity",
    "list_brand_backups",
    "restore_brand_backup",
    "get_active_brand",
    "set_active_brand",
    # product
    "get_products_dir",
    "get_product_dir",
    "load_product_index",
    "save_product_index",
    "create_product",
    "load_product",
    "load_product_summary",
    "save_product",
    "delete_product",
    "list_products",
    "list_product_images",
    "add_product_image",
    "delete_product_image",
    "set_primary_product_image",
    # project
    "get_projects_dir",
    "get_project_dir",
    "load_project_index",
    "save_project_index",
    "count_project_assets",
    "list_project_assets",
    "create_project",
    "load_project",
    "load_project_summary",
    "save_project",
    "delete_project",
    "list_projects",
    "get_active_project",
    "set_active_project",
    # style_reference
    "get_style_references_dir",
    "get_style_reference_dir",
    "load_style_reference_index",
    "save_style_reference_index",
    "create_style_reference",
    "load_style_reference",
    "load_style_reference_summary",
    "save_style_reference",
    "delete_style_reference",
    "list_style_references",
    "list_style_reference_images",
    "add_style_reference_image",
    "delete_style_reference_image",
    "set_primary_style_reference_image",
    "sync_style_reference_index",
    # document
    "get_docs_dir",
    "list_documents",
    "save_document",
    "delete_document",
    "rename_document",
    "load_image_status_raw",
    "save_image_status",
    "get_assets_dir",
    "list_assets",
    "save_asset",
]
# Re-export from submodules
from .base import (
    get_brand_dir,
    get_brands_dir,
    get_index_path,
    safe_resolve_path,
    slugify,
    validate_slug,
)
from .brand_storage import (
    backup_brand_identity,
    create_brand,
    delete_brand,
    get_active_brand,
    list_brand_backups,
    list_brands,
    load_brand,
    load_brand_summary,
    restore_brand_backup,
    save_brand,
    set_active_brand,
    update_brand_summary_stats,
)
from .document_storage import (
    delete_document,
    get_assets_dir,
    get_docs_dir,
    list_assets,
    list_documents,
    load_image_status_raw,
    rename_document,
    save_asset,
    save_document,
    save_image_status,
)
from .index import load_index, save_index
from .product_storage import (
    add_product_image,
    create_product,
    delete_product,
    delete_product_image,
    get_product_dir,
    get_products_dir,
    list_product_images,
    list_products,
    load_product,
    load_product_index,
    load_product_summary,
    save_product,
    save_product_index,
    set_primary_product_image,
)
from .project_storage import (
    count_project_assets,
    create_project,
    delete_project,
    get_active_project,
    get_project_dir,
    get_projects_dir,
    list_project_assets,
    list_projects,
    load_project,
    load_project_index,
    load_project_summary,
    save_project,
    save_project_index,
    set_active_project,
)
from .style_reference_storage import (
    add_style_reference_image,
    create_style_reference,
    delete_style_reference,
    delete_style_reference_image,
    get_style_reference_dir,
    get_style_references_dir,
    list_style_reference_images,
    list_style_references,
    load_style_reference,
    load_style_reference_index,
    load_style_reference_summary,
    save_style_reference,
    save_style_reference_index,
    set_primary_style_reference_image,
    sync_style_reference_index,
)
