"""Brand models - backward compatible re-exports."""

from .brand import (
    AudienceProfile,
    BrandCoreIdentity,
    BrandIdentityFull,
    BrandIndex,
    BrandIndexEntry,
    BrandSummary,
    ColorDefinition,
    CompetitivePositioning,
    TypographyRule,
    VisualIdentity,
    VoiceGuidelines,
)
from .product import (
    PackagingTextDescription,
    PackagingTextElement,
    ProductAttribute,
    ProductFull,
    ProductIndex,
    ProductSummary,
)
from .project import ProjectFull, ProjectIndex, ProjectStatus, ProjectSummary
from .style_reference import (
    AppearanceSpec,
    CanvasSpec,
    ColorGradingSpec,
    ConstraintSpec,
    ContentSpec,
    GeometrySpec,
    InteractionSpec,
    LayoutElement,
    LayoutStructureSpec,
    MessageSpec,
    ProductSlot,
    StyleReferenceAnalysis,
    StyleReferenceAnalysisV2,
    StyleReferenceAnalysisV3,
    StyleReferenceConstraintsSpec,
    StyleReferenceFull,
    StyleReferenceIndex,
    StyleReferenceSummary,
    StyleSpec,
    StyleSuggestionsSpec,
    VisualSceneSpec,
)
from .visual_directive import (
    ColorGuidelines,
    FeedbackInstance,
    FeedbackLog,
    LearnedRule,
    MoodGuidelines,
    PhotographyStyle,
    RuleScope,
    TargetRepresentation,
    VisualDirective,
)

__all__ = [
    # Brand models (11)
    "AudienceProfile",
    "BrandCoreIdentity",
    "BrandIdentityFull",
    "BrandIndex",
    "BrandIndexEntry",
    "BrandSummary",
    "ColorDefinition",
    "CompetitivePositioning",
    "TypographyRule",
    "VisualIdentity",
    "VoiceGuidelines",
    # Product models (6)
    "PackagingTextDescription",
    "PackagingTextElement",
    "ProductAttribute",
    "ProductFull",
    "ProductIndex",
    "ProductSummary",
    # Project models (4)
    "ProjectFull",
    "ProjectIndex",
    "ProjectStatus",
    "ProjectSummary",
    # StyleReference models (21)
    "AppearanceSpec",
    "CanvasSpec",
    "ColorGradingSpec",
    "ConstraintSpec",
    "ContentSpec",
    "GeometrySpec",
    "InteractionSpec",
    "LayoutElement",
    "LayoutStructureSpec",
    "MessageSpec",
    "ProductSlot",
    "StyleReferenceAnalysis",
    "StyleReferenceAnalysisV2",
    "StyleReferenceAnalysisV3",
    "StyleReferenceConstraintsSpec",
    "StyleReferenceFull",
    "StyleReferenceIndex",
    "StyleReferenceSummary",
    "StyleSpec",
    "StyleSuggestionsSpec",
    "VisualSceneSpec",
    # VisualDirective models (9)
    "ColorGuidelines",
    "FeedbackInstance",
    "FeedbackLog",
    "LearnedRule",
    "MoodGuidelines",
    "PhotographyStyle",
    "RuleScope",
    "TargetRepresentation",
    "VisualDirective",
]
