//QuickCreateStyleReferenceDialog - Minimal creation with auto-open to view
import{useState,useCallback}from'react'
import{Layout,X}from'lucide-react'
import{Button}from'@/components/ui/button'
import{FormDialog}from'@/components/ui/form-dialog'
import{Input}from'@/components/ui/input'
import{Dropzone,DropzoneEmptyState}from'@/components/ui/dropzone'
import{useStyleReferences}from'@/context/StyleReferenceContext'
import{useAsyncAction}from'@/hooks/useAsyncAction'
import{processImageFiles}from'@/lib/file-utils'
import type{ProcessedFile}from'@/lib/file-utils'
import{getAllowedImageExts}from'@/lib/constants'
import{toast}from'@/components/ui/toaster'
interface QuickCreateStyleReferenceDialogProps{open:boolean;onOpenChange:(open:boolean)=>void;onCreated?:(slug:string)=>void}
export function QuickCreateStyleReferenceDialog({open,onOpenChange,onCreated}:QuickCreateStyleReferenceDialogProps){
const{createStyleReference,refresh}=useStyleReferences()
const[name,setName]=useState('')
const[images,setImages]=useState<ProcessedFile[]>([])
const[uploadError,setUploadError]=useState<string|null>(null)
const handleFilesAdded=useCallback(async(files:File[])=>{setUploadError(null)
const{processed,rejected}=await processImageFiles(files)
if(rejected.length>0)setUploadError(`Unsupported: ${rejected.join(', ')}`)
//Only 1-2 images for quick create
const remaining=2-images.length
if(processed.length>remaining){setUploadError('Max 2 images');setImages(prev=>[...prev,...processed.slice(0,remaining)])}
else setImages(prev=>[...prev,...processed])},[images.length])
const handleDropError=useCallback((err:Error)=>{setUploadError(err.message||'Failed to add files')},[])
const removeImage=(idx:number)=>setImages(prev=>prev.filter((_,i)=>i!==idx))
const{execute,isLoading,error,clearError}=useAsyncAction(async()=>{
if(!name.trim())throw new Error('Please enter a name')
if(images.length===0)throw new Error('Please add a reference image')
const imageData=images.map(({file,base64})=>({filename:file.name,data:base64}))
//Create with default settings: defaultStrict=true, description auto-generated by AI
const slug=await createStyleReference({name:name.trim(),description:'',images:imageData,defaultStrict:true})
await refresh();toast.success(`Style Reference "${name.trim()}" created`)
onCreated?.(slug);onOpenChange(false);setName('');setImages([])})
const handleClose=useCallback(()=>{if(!isLoading){onOpenChange(false);setName('');setImages([]);clearError();setUploadError(null)}},[isLoading,onOpenChange,clearError])
const combinedError=error||uploadError
return(<FormDialog open={open} onOpenChange={handleClose} title="Quick Add Style Reference" description="Add a reference image. AI will analyze the visual style." icon={<Layout className="h-5 w-5"/>} iconColor="text-brand-500" isLoading={isLoading} loadingMessage="Creating style reference..." error={combinedError} onClearError={()=>{clearError();setUploadError(null)}} maxWidth="max-w-md" footer={<>
<Button variant="outline" onClick={handleClose} disabled={isLoading}>Cancel</Button>
<Button onClick={()=>execute()} disabled={isLoading||!name.trim()||images.length===0} className="bg-brand-500 hover:bg-brand-600">{isLoading?'Creating...':'Add Style Reference'}</Button>
</>}>
{/*Name Input*/}
<div className="space-y-2">
<label htmlFor="quick-style-ref-name" className="text-sm font-medium">Name <span className="text-destructive">*</span></label>
<Input id="quick-style-ref-name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g., Hero Banner Style" autoFocus/>
</div>
{/*Image Dropzone*/}
<div className="space-y-2">
<label className="text-sm font-medium">Reference Image <span className="text-destructive">*</span></label>
{images.length===0?(<Dropzone accept={{'image/*':getAllowedImageExts()}} maxFiles={2} onDrop={handleFilesAdded} onError={handleDropError} className="border-dashed">
<DropzoneEmptyState><div className="flex flex-col items-center"><p className="text-sm mb-1">Drag & drop reference image</p><p className="text-xs text-muted-foreground">PNG, JPG, GIF, WebP</p></div></DropzoneEmptyState>
</Dropzone>):(<div className="flex flex-wrap gap-2">
{images.map((item,idx)=>(<div key={idx} className="relative group">
<img src={item.dataUrl} alt={item.file.name} className="h-20 w-20 rounded object-cover border"/>
<button type="button" onClick={()=>removeImage(idx)} className="absolute -top-1 -right-1 h-5 w-5 bg-destructive text-white rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"><X className="h-3 w-3"/></button>
<span className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-[10px] px-1 truncate rounded-b">{item.file.name}</span>
</div>))}
{images.length<2&&(<Dropzone accept={{'image/*':getAllowedImageExts()}} maxFiles={2-images.length} onDrop={handleFilesAdded} onError={handleDropError} className="h-20 w-20 border-dashed flex items-center justify-center">
<DropzoneEmptyState><span className="text-2xl text-muted-foreground">+</span></DropzoneEmptyState></Dropzone>)}
</div>)}
</div>
</FormDialog>)}
